wesbos/cobalt2-vscode

- theme/cobalt2.json
made the ruler much less intrusive
made whitespace visible if requested (https://github.com/wesbos/cobalt2-vscode/issues/6)
before:
after:
> added distinction between php entities and  storage

- theme/cobalt2.json
Hi Wes,
I have fixed an issue highlighted in issue #44 where command line parameters/flags where appearing in black and therefore not readable against the darker terminal background.
My fix addresses this and uses the blue #0050A4 used elsewhere as a selection colour. The fix addresses the visibility issue of parameters/flags when typed and also whenever the user makes a selection.
Thanks,
Alisdair
> Terminal parameter/flag colours

- theme/cobalt2.json
Applying Cobalt2 colors to Git file decorations in File Explorer.
`theme/cobalt2.json` Modified.
`newfile.js` Untracked.
`node_modules` Ignored.
`css.css` Conflicting.
> Add support for git status colors in file explorer

- README.md
- cobalt2-custom-hacks.css
The CSS hack for making the fat cursor is no longer working after updating to v1.20, plus in the same release we can control cursor width natively via using `editor.cursorWidth` settings.
Everyone can enjoy the fat cursor now without using the `.vscodestyles.css` file anymore! 🙌
> Fix Fat Cursor VS Code V1.20

- theme/cobalt2.json
> Added a border to the peek section and removed the black background in the peek match.

- theme/cobalt2.json
> Darker colors for inserted/removed text background

- theme/cobalt2.json
The italics in HTML tag attributes were showing only in .jsx and .html files, but not in in Razor and Twig (and possibly other html dialects).
> Added color to C# attributes (annotations) and italics to HTML attributes

- cobalt2-custom-hacks.css
Adopted the vanilla vs-code stylings and displays the shadow permanently if minimap is enabled.
> Added small inset shadow onto minimap scrollbar #71

- package-lock.json
- theme/cobalt2.json
@wesbos Suggestion from issue was to change the color of the closing tag to make it more deeper and visible and then take a look at making the editor text highlight color more vibrant. 
Couldn't change the color of the closing tag to be deeper without changing the color of the opening tag. So to make it more visible editor text highlight color changed so it wouldn't be as faint as it was and allow the closing tag to be visible when the matching opening tag is selected. 
Before: 
After:
Closes #68
> FIX: HTML closing tag selected color should be more deep. #68

- theme/cobalt2.json
- Change active debugging foreground text color to theme yellow.
- Change active debugging top border color to theme yellow.
- Keep the default top border color when no folder is selected (missing rule).
- Format values that are arrays into one line.
This closes #96
> Fixes Issue 96 - Status Bar Styling for Active Debug

- theme/cobalt2.json
Added some transparency to the match background in order to make numbers more readable.
Should fix #104 and fix #101
> Adding transparency to match background #104

- theme/cobalt2.json
* Changes right click menu color to something different than the editor background color
* Changes inactive selection color to something different than the editor background color
Here is a screenshot for comparison
This closes #124 and closes #127
> Fixes #124 and #127

- theme/cobalt2.json
Request to add support for JSX text nodes which currently display with the same color as Tag Names, #9effff. This can be seen when viewing the below file with Cobalt2 enabled:
```
class Example extends React.Component {
render() {
return (
<div>
<span>Example of Syntax Highlighting</span>
</div>
);
}
}
```
The "Example of Syntax Highlighting" text should appear in blue rather than white as it does with standard HTML.
> Added JSX Text support

- theme/cobalt2.json
The highlighting for csharp was not very easy to read with a lot of things being the same color. I've tweaked it a bit to have things be different where they should be.
Before: 
After:
> Add csharp specific highlighting

- theme/cobalt2.json
fixes #93 
**Before:**
**After:**
> Fix gitignore files showing as bright pink

- cobalt2-custom-hacks.css
This PR adjusts the selector and CSS properties for the dirty tab circle and cross (hover while in dirty state).
> Update CSS for dirty tab circle / cross

- theme/cobalt2.json
Swapping the active and inactive tab colours might be a good idea. Just to follow the common design convention of having the tab colour match the background of the currently selected tab.
Was finding there was some confusion when only 2 tabs were open. With more tabs open this change doesn't matter as much. Could be worth thinking about, even if this change doesn't make it upstream.
> Invert tab colours to follow common design convention

- theme/cobalt2.json
The whitespace characters was really hard to see. Made then brighter.
> Made whitespace characters brighter.

- theme/cobalt2.json
This PR implements support for `editorInlayHint` via https://github.com/wesbos/cobalt2-vscode/issues/198.
> add support for editorInlayHint

- theme/cobalt2.json
In the diff editor, the borders around the lines -and parts of lines- added or removed can be a bit overwhelming.
I propose to remove them, and think the result is much cleaner, which improves the diff editor experience overall.
(note that the lines with borders seen here are where the cursor is positioned)
(note that the lines with borders seen here are where the cursor is positioned)
> Removed distracting borders on the changed parts in the diff editor

- theme/cobalt2.json
- The issue required the need to change the color of the scroll-bar when it is not being hovered as it was difficult to find when working on large files.
- I have completed this.
-I changed the scroll-bar color to the color that was given to the `highlighted scrollbar` then I gave a new color to the `highlighted scrollbar`.
- This way when working on documents, it is easy to see the scrollbar.
> changed scroll-bar color to be more visible

- theme/cobalt2.json
+ This commit addresses issue #200 
Fixed an issue where text under the terminal cursor would be invisible.
Previous version: 
This version:
> [FIX] Terminal cursor background colour

- theme/cobalt2.json
Hey, @wesbos — Happy hacktoberfest to you good sir! 
This PR addresses issue #185 reported by @kingcard1131.
Here is a before and after:
I discovered these new token scopes by digging thru https://github.com/primer/github-vscode-theme/blob/a9acf82f22bf810baf445b6efe5689aa89b4949c/src/theme.js#L487-L508... very informative. Also they have a really sweet theming setup over there 😻 if you've not seen it, check it out.
Thanks for considering!
> adds colors to support gitlens hover

- theme/cobalt2.json
This commit fixes issue #220 and makes the ```statusBarItem.remoteBackground``` and ```statusBarItem.remoteForeground``` colors match the rest of the status bar so that it doesn't weirdly stand out. 
Only third time committing to a repository that isn't my own, and first time doing it without help, let me know if I messed something up or if this was ok.
Stephen
P.S. Love Syntax, thanks for all you guys do.
> make statusBar.remote colors look normal

- theme/cobalt2.json
Use a lighter red. (in https://github.com/wesbos/cobalt2-vscode/issues/234#issuecomment-1717775146)
Problem:
I find `console.error` and `console.warn` share the same foreground color. Is it the expected behavior? I guess that VS Code define the same API for the two types of output in REPL.
> fix: debug console error color (#234)

- theme/cobalt2.json
It's hard to spot checkboxes in the settings UI.
This PR adds a border to checkboxes.
👆 BEFORE
👇 AFTER
> Add border to checkboxes in settings UI
